// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enkstaldgdbumxsdjioa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVua3N0YWxkZ2RidW14c2RqaW9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyNjg2OTIsImV4cCI6MjA1NTg0NDY5Mn0.U-44h_auIcLVGxrFwo5jIM2Hvk7CDkpDG6WwboDjPZ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);